# Generated by Django 5.1.4 on 2024-12-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100, verbose_name="ФИО")),
                (
                    "team_id",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Номер бригады"
                    ),
                ),
                (
                    "salary",
                    models.PositiveIntegerField(verbose_name="Заработная плата"),
                ),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("1", "Черновая отделка"),
                            ("2", "Чистовая отделка"),
                            ("3", "Бригадир"),
                            ("4", "Прораб"),
                        ],
                        default="3",
                        max_length=100,
                        verbose_name="Специализация",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рабочий",
                "verbose_name_plural": "Рабочие",
                "ordering": ["full_name"],
            },
        ),
    ]
